### ISSUE TITLE
Interest in supporting Scala 2.10?

### ISSUE THREAD

**Issue by ivern** [soc/scala-java-time#39] opened 2016-08-04 03:18 UTC
I needed a java.time implementation compatible with Scala 2.10 (for a library that needs to run both within Spark and in Scala.js).  I've gotten most of the way there in a fork:

https://github.com/ivern/scala-java-time

The port is basically complete, minus a few failing tests (4 failing tests in 2.11, 33 in 2.10).  Are you interested in a pull request if I sort out the remaining test failures?  If so, I'll go ahead and sort those issues out.

**Comment by soc** [comment] 2016-08-04 11:46
Yes, absolutely! Very confusing, I thought I was testing/building for 2.10 already! Thanks alot!

**Comment by ivern** [comment] 2016-08-04 13:31
Awesome.  Current status of failing tests:

* All tests in `TestTzdbZoneRulesCompiler` are failing in 2.10.  I haven't looked into this very deeply yet, but it looks like a reflection issue in the test suite.  I'll get this sorted out before submitting a PR.

* Four tests are failing in `TestDateTimeFormatter` in all Scala versions.  I already know what the problem is here--I accidentally swapped the argument names in `SimpleDateTimeTextProvider.COMPARATOR`.  I'll also get this sorted out before submitting a PR.

**Comment by ivern** [comment] 2016-08-04 13:32
For the PR, should I also modify the README to include references to 2.10 support and whatnot?

**Comment by ivern** [comment] 2016-08-04 13:42
One more question: you asked in my repo if I had sourced the SAM changes from the threeten repo.  I have not, I wrote them independently to address the build failures I encountered in 2.10.  Let me know if you'd prefer I do this differently.

**Comment by soc** [comment] 2016-08-04 13:51
@ivern

> TestTzdbZoneRulesCompiler are failing

I think I know the reasons, let me find the line for you. Name mangling has changed between versions, and I'm pretty sure when I did the hack I didn't check for 2.10 ...

> modify the README

Sure, that would be nice!

> SAM changes

- No, it's fine, but you can use the threetenbp sources to crosscheck that no silly mistakes happened when backporting the SAMs.

**Comment by soc** [comment] 2016-08-04 13:51
Here it is: https://github.com/soc/scala-java-time/blob/master/jvm/src/test/scala/org/threeten/bp/zone/TestTzdbZoneRulesCompiler.scala#L77

**Comment by soc** [comment] 2016-08-04 13:52
Just change the line that reads

> if (scalaVersion.startsWith("2.11"))

to

> if (scalaVersion.startsWith("2.11") || scalaVersion.startsWith("2.10"))

**Comment by soc** [comment] 2016-08-04 13:55
While you're changing the build config, could you drop the `-Xexperimental` flag, that was added to support SAMs? If we did everything correctly, it should now compile without it.

**Comment by ivern** [comment] 2016-08-04 15:02
All changes made as requested and PR submitted.  Let me know what you think.  Thanks for the feedback!

**Comment by ivern** [comment] 2016-08-04 15:03
FYI, 158 tests fail for 2.12 (all in `org.threeten.bp.format.TestDateTimeFormatters`) but as far as I can tell these failures exist in the current master branch and weren't added by the backport.

**Comment by ivern** [comment] 2016-08-04 15:08
Interesting, the Travis build succeeded.  Looks like it's not running tests against the cross-compile targets.  If you switch it to run sbt +test, it should succeed for 2.10 and 2.11 but fail for 2.12 (as mentioned above, this appears to be pre-existing).

**Comment by soc** [comment] 2016-08-04 16:17
Oh, yes, just seeing it. Any ideas?

**Comment by soc** [comment] 2016-08-04 16:18
Oh, weird. I thought I fixed that in https://github.com/soc/scala-java-time/commit/f30a74613f86e2950fbccc1a34030369b31bb1a5 ...

**Comment by ivern** [comment] 2016-08-04 18:33
I'll have a look tonight to see if I can figure it out.  Thanks for merging the PR, by the way--do you have a timeline for publishing the 2.10 artifact to Maven central?

**Comment by soc** [comment] 2016-08-04 19:26
I'd like to see whether the issue on 2.12 can be found/fixed in a reasonable amount of time (a few days) so I can release all three versions at the same time.

If the issue is found -> fix and release, if not -> release without fix.
I also asked on scala/contributors on Gitter whether the boxing behavior has changed.

**Comment by soc** [comment] 2016-08-04 19:27
Reverting f30a746 reintroduces the issue on 2.11, so I think it's related to some boxing/compiler changes, because 2.11 and 2.12 shouldn't behave differently.

**Comment by soc** [comment] 2016-08-09 13:28
@ivern I just pushed 2.0.0-M3, and it should be available shortly. Give it a try!

**Comment by ivern** [comment] 2016-08-09 18:36
Just upgraded my project to using this, and it's working well.  Thank you!

**Comment by soc** [comment] 2016-08-16 02:13
Great! I'll close this! Please file individual bugs if you encounter issues!

**Closed** 2016-09-12 06:34 UTC
